[package]
name = "email-newsletter"
version = "0.1.0"
edition = "2024"

[lib]
name = "email_newsletter"
path = "src/lib.rs"

[dependencies]
actix-web = "4.12.1"
anyhow = "1.0.100"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }

[dev-dependencies]
reqwest = "0.12.28"
